# Generated by Django 4.2.17 on 2025-01-11 21:18

from django.db import migrations
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_create_homepage'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='medical_news',
            field=wagtail.fields.StreamField([('medical_news', 0)], blank=True, block_lookup={0: ('filterable_pagechooser.blocks.FilterPageChooserBlock', (), {'filters_info': 'filters_info:type=medical;is_active=True', 'label': 'Medical Articles', 'page_type': ['article.Article']})}, default='', verbose_name='Medical News'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='sport_news',
            field=wagtail.fields.StreamField([('sport_news', 0)], blank=True, block_lookup={0: ('filterable_pagechooser.blocks.FilterPageChooserBlock', (), {'filters_info': 'filters_info:type=sport;is_active=True', 'label': 'Sport Articles', 'page_type': ['article.Article']})}, default='', verbose_name='Sport News'),
        ),
    ]
